######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 5 17:28:25 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += simulation.h
SOURCES += qt.cpp
